Repository QuokkaWallaby/Recorder-Project, pull requests merged in 2022-04, with the labels that each got.

#101 feat: 카테고리 기능 구현(수정 필요)
  backend/frontend/src/components/Category/Category.js
  backend/frontend/src/components/Category/CategoryList.js
  backend/frontend/src/components/Category/CreateCategory.js
  backend/frontend/src/components/Category/index.js
  backend/frontend/src/redux/actions/category.js
  backend/frontend/src/redux/actions/types.js
  backend/frontend/src/redux/reducers/category.js
  backend/frontend/src/redux/reducers/index.js
  backend/frontend/src/services/category.service.js
Labels: 🌷 프론트, 🕹 기능

#102 refactor: 카테고리부분 UI수정
  backend/frontend/src/components/Userhome/Sidebar.js
Labels: 🌷 프론트, 📱 유아이, 🛠 리팩토링

#104 feat: 카테고리 조회, 추가 기능 수정
  backend/frontend/src/components/Category/Category.js
  backend/frontend/src/redux/actions/category.js
  backend/frontend/src/redux/reducers/category.js
  backend/frontend/src/services/category.service.js
  backend/src/main/java/com/record/backend/repository/CategoryRepository.java
Labels: 🌷 프론트, 🛠 리팩토링, 🕹 기능

#111 fix: 유저 프로필 사진 디비 추가 안되는거 수정
  backend/src/main/java/com/record/backend/apiController/UserApiController.java
  backend/src/main/java/com/record/backend/aws/FileUploadResponse.java
  backend/src/main/java/com/record/backend/aws/S3Uploader.java
  backend/src/main/java/com/record/backend/dto/user/response/UserResponseDto.java
Labels: 🚐 핫픽스, 🔥 백엔드, 🐞 버그, 🛠 리팩토링, 🕹 기능

#112 fix: s3 key부분 하드코딩 수정
  backend/src/main/java/com/record/backend/aws/S3Uploader.java
Labels: 🚐 핫픽스, 🔥 백엔드

#113 feat: 유효성 검사 추가
  frontend/src/components/Header/Header.js
  frontend/src/components/Header/UserHeader.js
  frontend/src/img/logo-removebg.png
  frontend/src/pages/Signup.js
Labels: 🌷 프론트, 🛠 리팩토링, 🕹 기능

#114 feat: find user all posts 메서드 작성
  backend/src/main/java/com/record/backend/apiController/PostApiController.java
  backend/src/main/java/com/record/backend/dto/post/response/PostAllUserResponseDto.java
  backend/src/main/java/com/record/backend/dto/post/response/PostAllUsersResponseDto.java
  backend/src/main/java/com/record/backend/repository/PostRepository.java
  backend/src/main/java/com/record/backend/service/PostService.java
Labels: 🔥 백엔드, 🛠 리팩토링, 🕹 기능

#115 fix: UI 수정
  frontend/src/App.js
  frontend/src/fonts/Pretendard.ttf
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/pages/Editor.js
  frontend/src/pages/Main.js
  frontend/src/pages/Signup.js
  frontend/src/pages/User.js
Labels: 🚐 핫픽스, 🌷 프론트, 📱 유아이

#120 fix: 헤더 링크 수정
  frontend/src/components/Header/UserHeader.js
Labels: 🚐 핫픽스, 🌷 프론트
