Repository QuokkaWallaby/Recorder-Project, pull requests merged in 2022-03, with the labels that each got.

#59 Test
  backend/src/main/java/com/record/backend/BackendApplication.java
  backend/src/main/java/com/record/backend/apiController/CommentApiController.java
  backend/src/main/java/com/record/backend/domain/comment/Comment.java
  backend/src/main/java/com/record/backend/domain/comment/CommentContent.java
  backend/src/main/java/com/record/backend/domain/comment/Comments.java
  backend/src/main/java/com/record/backend/domain/neighbor/Neighbor.java
  backend/src/main/java/com/record/backend/domain/post/Post.java
  backend/src/main/java/com/record/backend/domain/post/PostLike.java
  backend/src/main/java/com/record/backend/domain/post/Posts.java
  backend/src/main/java/com/record/backend/domain/user/User.java
  backend/src/main/java/com/record/backend/domain/user/follow/Follow.java
  backend/src/main/java/com/record/backend/dto/comment/CommentDto.java
  backend/src/main/java/com/record/backend/dto/comment/CommentResponseDto.java
  backend/src/main/java/com/record/backend/repository/comment/CommentRepository.java
  backend/src/main/java/com/record/backend/repository/tag/TagRepository.java
  backend/src/main/java/com/record/backend/repository/user/UserRepository.java
  backend/src/main/java/com/record/backend/service/CommentService.java
  backend/src/test/java/com/record/backend/service/PostServiceTest.java
  recorder로고/facebook_cover_photo_1.png
  recorder로고/facebook_cover_photo_2.png
  recorder로고/facebook_profile_image.png
  recorder로고/favicon.png
  recorder로고/instagram_profile_image.png
  recorder로고/linkedin_banner_image_1.png
  recorder로고/linkedin_banner_image_2.png
  recorder로고/linkedin_profile_image.png
  recorder로고/logo.png
  recorder로고/logo_transparent.png
  recorder로고/pinterest_board_photo.png
  recorder로고/pinterest_profile_image.png
  recorder로고/twitter_header_photo_1.png
  recorder로고/twitter_header_photo_2.png
  recorder로고/twitter_profile_image.png
  recorder로고/youtube_profile_image.png
Labels: 🔥 백엔드, 🛠 리팩토링

#63 fix: signup 수정 완료
  backend/src/main/java/com/record/backend/apiController/UserApiController.java
  backend/src/main/java/com/record/backend/controller/MemberController.java
  backend/src/main/java/com/record/backend/service/PostService.java
  frontend/src/components/Signup/actions/action.js
  frontend/src/pages/Signup.js
Labels: 🚐 핫픽스, 🌷 프론트, 🔥 백엔드

#77 refactor: 로그인, 회원가입 기능 리팩토링
  backend/build.gradle
  backend/frontend/package.json
  backend/frontend/src/components/Login/actions/action.js
  backend/frontend/src/components/Login/actions/types.js
  backend/frontend/src/components/Login/reducers/index.js
  backend/frontend/src/components/Login/reducers/reducer.js
  backend/frontend/src/components/Signup/actions/action.js
  backend/frontend/src/components/Signup/actions/types.js
  backend/frontend/src/components/Signup/reducers/reducer.js
  backend/frontend/src/index.js
  backend/frontend/src/pages/Login.js
  backend/frontend/src/pages/Signup.js
  backend/frontend/src/redux/actions/auth.js
  backend/frontend/src/redux/actions/message.js
  backend/frontend/src/redux/actions/types.js
  backend/frontend/src/redux/reducers/auth.js
  backend/frontend/src/redux/reducers/index.js
  backend/frontend/src/redux/reducers/message.js
  backend/frontend/src/redux/store.js
  backend/frontend/src/services/auth-header.js
  backend/frontend/src/services/auth.service.js
Labels: 🌷 프론트, 🛠 리팩토링

#83 feat: UserHeader 추가, logout 기능 구현
  backend/frontend/src/App.js
  backend/frontend/src/components/Header/Header.js
  backend/frontend/src/components/Header/UserHeader.js
Labels: 🌷 프론트, 🕹 기능

#85 feat: 프로필페이지추가
  backend/frontend/src/App.js
  backend/frontend/src/pages/Profile.js
Labels: 🌷 프론트, 📱 유아이

#89 feat: s3 프로필 업로드시 앞단에 넘겨주는 response entity 작성
  backend/bin/main/com/record/backend/apiController/UserApiController$Result.class
  backend/bin/main/com/record/backend/apiController/UserApiController.class
  backend/bin/main/static/asset-manifest.json
  backend/bin/main/static/favicon.ico
  backend/bin/main/static/index.html
  backend/bin/main/static/logo192.png
  backend/bin/main/static/logo512.png
  backend/bin/main/static/manifest.json
  backend/bin/main/static/robots.txt
  backend/bin/main/static/static/css/main.033ccf6d.css
  backend/bin/main/static/static/css/main.033ccf6d.css.map
  backend/bin/main/static/static/css/main.82d8aa55.css
  backend/bin/main/static/static/css/main.82d8aa55.css.map
  backend/bin/main/static/static/js/787.9750ae9a.chunk.js
  backend/bin/main/static/static/js/787.9750ae9a.chunk.js.map
  backend/bin/main/static/static/js/main.602b4daf.js
  backend/bin/main/static/static/js/main.602b4daf.js.LICENSE.txt
  backend/bin/main/static/static/js/main.602b4daf.js.map
  backend/bin/main/static/static/js/main.bb66a4c8.js
  backend/bin/main/static/static/js/main.bb66a4c8.js.LICENSE.txt
  backend/bin/main/static/static/js/main.bb66a4c8.js.map
  backend/bin/main/static/static/js/main.e59e26bc.js
  backend/bin/main/static/static/js/main.e59e26bc.js.LICENSE.txt
  backend/bin/main/static/static/js/main.e59e26bc.js.map
  backend/src/main/java/com/record/backend/apiController/UserApiController.java
  backend/src/main/java/com/record/backend/aws/S3Uploader.java
Labels: 🔥 백엔드, 🕹 기능

#90 fix: 로그인 api 리턴 부분 수정
  backend/src/main/java/com/record/backend/auth/controller/login/AuthController.java
  backend/src/main/java/com/record/backend/dto/loginlogout/response/JwtAuthenticationResponse.java
Labels: 🔥 백엔드, 🛠 리팩토링

#91 fix: 깃이그노어 안되는거 수정
  .gitignore
  backend/src/main/resources/application-credentials.yml
Labels: ⚙️ 설정

#99 fix: editor 기능 구현
  .idea/runConfigurations.xml
  .idea/vcs.xml
  backend/.gradle/7.3.2/checksums/checksums.lock
  backend/.gradle/7.3.2/checksums/md5-checksums.bin
  backend/.gradle/7.3.2/checksums/sha1-checksums.bin
  backend/.idea/gradle.xml
  backend/.idea/modules/backend.main.iml
  backend/.idea/modules/backend.test.iml
  backend/frontend/src/pages/Editor.js
  backend/frontend/src/pages/Profile.js
  backend/frontend/src/redux/actions/auth.js
  backend/frontend/src/redux/actions/types.js
  backend/frontend/src/redux/reducers/auth.js
  backend/frontend/src/services/auth.service.js
  backend/src/main/java/com/record/backend/auth/service/RefreshTokenService.java
  backend/src/main/java/com/record/backend/dto/post/request/PostSaveRequestDto.java
Labels: 🚐 핫픽스, 🌷 프론트, 🔥 백엔드, 🕹 기능
