Repository QuokkaWallaby/Recorder-Project, pull requests merged in 2022-02, with the labels that each got.

#23 Test
  backend/src/main/java/com/record/backend/domain/Alert.java
  backend/src/main/java/com/record/backend/domain/Category.java
  backend/src/main/java/com/record/backend/domain/comment/Comment.java
  backend/src/main/java/com/record/backend/domain/comment/CommentLike.java
  backend/src/main/java/com/record/backend/domain/post/Post.java
  backend/src/main/java/com/record/backend/domain/post/PostCategory.java
  backend/src/main/java/com/record/backend/domain/post/PostLike.java
  backend/src/main/java/com/record/backend/domain/post/PostTag.java
Labels: 🔥 백엔드

#25 feat: 도메인 엔티티 양방향 연관관계 메서드 추가
  backend/src/main/java/com/record/backend/domain/Category.java
  backend/src/main/java/com/record/backend/domain/comment/Comment.java
Labels: 🔥 백엔드

#27 refactor: 도메인 엔티티 코드 리팩토링
  backend/build.gradle
  backend/src/main/java/com/record/backend/domain/Alert.java
  backend/src/main/java/com/record/backend/domain/Category.java
  backend/src/main/java/com/record/backend/domain/Tag.java
  backend/src/main/java/com/record/backend/domain/User.java
  backend/src/main/java/com/record/backend/domain/comment/Comment.java
  backend/src/main/java/com/record/backend/domain/comment/CommentLike.java
  backend/src/main/java/com/record/backend/domain/post/Post.java
  backend/src/main/java/com/record/backend/domain/post/PostCategory.java
  backend/src/main/java/com/record/backend/domain/post/PostLike.java
  backend/src/main/java/com/record/backend/domain/post/PostTag.java
  backend/src/test/java/com/record/backend/MemberRepositoryTest.java
Labels: 🔥 백엔드, 🛠 리팩토링

#28 feat: 사용자 홈페이지 UI 구현
  frontend/src/App.js
  frontend/src/pages/UserHome/MainPost.js
  frontend/src/pages/UserHome/Sidebar.js
  frontend/src/pages/UserHome/index.js
Labels: 🌷 프론트, 📱 유아이

#31 feat: 유저 폼 클래스 생성
  backend/src/main/java/com/record/backend/domain/comment/CommentLike.java
  backend/src/main/java/com/record/backend/domain/user/User.java
  backend/src/main/java/com/record/backend/domain/user/UserForm.java
  backend/src/main/java/com/record/backend/exception/IllegalUserException.java
Labels: 🔥 백엔드, 🛠 리팩토링

#33 feat: 카테고리 UI 구현
  frontend/src/components/Category/CategoryList.js
  frontend/src/components/Category/CreateCategory.js
  frontend/src/components/Category/index.js
  frontend/src/components/Modal/Modal.css
  frontend/src/components/Modal/Modal.js
  frontend/src/pages/UserHome/Sidebar.js
Labels: 🌷 프론트, 📱 유아이

#34 test(post): 게시글 테스트 케이스 작성
  backend/src/main/java/com/record/backend/apiController/PostApiController.java
  backend/src/main/java/com/record/backend/controller/PostController.java
  backend/src/main/java/com/record/backend/domain/post/Post.java
  backend/src/main/java/com/record/backend/repository/PostRepository.java
  backend/src/main/java/com/record/backend/repository/dto/PostResponseDto.java
  backend/src/main/java/com/record/backend/repository/dto/PostSaveRequestDto.java
  backend/src/main/java/com/record/backend/service/PostService.java
  backend/src/test/java/com/record/backend/repository/PostRepositoryTest.java
Labels: 🔥 백엔드, 🧩 테스트, 🛠 리팩토링

#38 test: member 데이터 테스트
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/index.js
Labels: 🌷 프론트, 🐞 버그, 🧩 테스트

#39 feat(Comment, Post): 연관관계 편이 메서드 추가
  backend/src/main/java/com/record/backend/domain/comment/Comment.java
  backend/src/main/java/com/record/backend/domain/post/Post.java
Labels: 🔥 백엔드

#41 refactor: post test를 위한 member repository 임시 삭제
  backend/src/main/java/com/record/backend/repository/dto/PostResponseDto.java
  backend/src/main/java/com/record/backend/repository/dto/PostSaveRequestDto.java
  backend/src/test/java/com/record/backend/MemberRepositoryTest.java
  backend/src/test/java/com/record/backend/repository/PostRepositoryTest.java
Labels: 🔥 백엔드, 🧩 테스트, 🛠 리팩토링

#42 feat(PostService): 필요 로직 추가, 내부 코드 작성 전
  backend/src/main/java/com/record/backend/apiController/PostApiController.java
  backend/src/main/java/com/record/backend/domain/user/User.java
  backend/src/main/java/com/record/backend/repository/PostRepository.java
  backend/src/main/java/com/record/backend/repository/UserRepository.java
  backend/src/main/java/com/record/backend/repository/dto/PostDto.java
  backend/src/main/java/com/record/backend/service/PostService.java
  backend/src/main/java/com/record/backend/service/UserService.java
  backend/src/test/java/com/record/backend/repository/PostRepositoryTest.java
Labels: 🔥 백엔드, 🧩 테스트

#44 feat: category 서비스, 레포지토리, 컨트롤러, dto 생성
  backend/src/main/java/com/record/backend/apiController/CategoryApiController.java
  backend/src/main/java/com/record/backend/controller/CategoryController.java
  backend/src/main/java/com/record/backend/domain/category/Category.java
  backend/src/main/java/com/record/backend/repository/CategoryRepository.java
  backend/src/main/java/com/record/backend/repository/dto/CategoryResponseDto.java
  backend/src/main/java/com/record/backend/repository/dto/CategorySaveRequestDto.java
  backend/src/main/java/com/record/backend/service/CategoryService.java
Labels: 🔥 백엔드, 🛠 리팩토링

#45 feat: 카테고리 api 컨트롤러 작성
  backend/src/main/java/com/record/backend/apiController/CategoryApiController.java
  backend/src/main/java/com/record/backend/domain/category/Category.java
  backend/src/main/java/com/record/backend/repository/CategoryRepository.java
  backend/src/main/java/com/record/backend/repository/dto/CategoryResponseDto.java
  backend/src/main/java/com/record/backend/repository/dto/CategorySaveRequestDto.java
  backend/src/main/java/com/record/backend/service/CategoryService.java
Labels: 🔥 백엔드

#46 feat(controller): comment 컨트롤러 작성
  backend/src/main/java/com/record/backend/apiController/CommentApiController.java
  backend/src/main/java/com/record/backend/domain/comment/Comment.java
  backend/src/main/java/com/record/backend/repository/CommentRepository.java
  backend/src/main/java/com/record/backend/repository/dto/CommentResponseDto.java
  backend/src/main/java/com/record/backend/repository/dto/CommentSaveRequestDto.java
  backend/src/main/java/com/record/backend/service/CommentService.java
Labels: 🔥 백엔드

#49 test(category, comment): 댓글 기능 테스트 레이아웃
  backend/src/main/java/com/record/backend/apiController/CategoryApiController.java
  backend/src/main/java/com/record/backend/apiController/CommentApiController.java
  backend/src/main/java/com/record/backend/apiController/UserApiController.java
  backend/src/main/java/com/record/backend/controller/UserController.java
  backend/src/main/java/com/record/backend/domain/category/Category.java
  backend/src/main/java/com/record/backend/domain/user/User.java
  backend/src/main/java/com/record/backend/repository/UserRepository.java
  backend/src/main/java/com/record/backend/repository/dto/CategoryResponseDto.java
  backend/src/main/java/com/record/backend/repository/dto/CategorySaveRequestDto.java
  backend/src/main/java/com/record/backend/repository/dto/UserResponseDto.java
  backend/src/main/java/com/record/backend/repository/dto/UserSaveRequestDto.java
  backend/src/main/java/com/record/backend/service/CategoryService.java
  backend/src/main/java/com/record/backend/service/CommentService.java
  backend/src/main/java/com/record/backend/service/UserService.java
  backend/src/test/java/com/record/backend/service/CategoryServiceTest.java
  backend/src/test/java/com/record/backend/service/CommentServiceTest.java
Labels: 🔥 백엔드, 🧩 테스트

#54 refactor: 레포지토리 위치 수정으로 인한 리팩토링
  backend/build.gradle
  backend/src/main/java/com/record/backend/BackendApplication.java
  backend/src/main/java/com/record/backend/apiController/CategoryApiController.java
  backend/src/main/java/com/record/backend/apiController/PostApiController.java
  backend/src/main/java/com/record/backend/apiController/UserApiController.java
  backend/src/main/java/com/record/backend/domain/BaseEntity.java
  backend/src/main/java/com/record/backend/domain/post/Post.java
  backend/src/main/java/com/record/backend/domain/post/PostLike.java
  backend/src/main/java/com/record/backend/domain/post/PostTag.java
  backend/src/main/java/com/record/backend/domain/tag/Tag.java
  backend/src/main/java/com/record/backend/domain/tag/TagName.java
  backend/src/main/java/com/record/backend/domain/tag/Tags.java
  backend/src/main/java/com/record/backend/domain/user/User.java
  backend/src/main/java/com/record/backend/domain/user/UserForm.java
  backend/src/main/java/com/record/backend/dto/post/PostSaveRequestDto.java
  backend/src/main/java/com/record/backend/dto/post/PostUpdateDto.java
  backend/src/main/java/com/record/backend/dto/tag/TagDto.java
  backend/src/main/java/com/record/backend/dto/tag/TagRequest.java
  backend/src/main/java/com/record/backend/dto/tag/TagResponse.java
  backend/src/main/java/com/record/backend/dto/user/UserModifyDto.java
  backend/src/main/java/com/record/backend/repository/category/CategoryRepository.java
  backend/src/main/java/com/record/backend/repository/comment/CommentRepository.java
  backend/src/main/java/com/record/backend/repository/post/PostRepository.java
  backend/src/main/java/com/record/backend/repository/post/PostTagRepository.java
  backend/src/main/java/com/record/backend/repository/tag/TagRepository.java
  backend/src/main/java/com/record/backend/repository/user/UserRepository.java
  backend/src/main/java/com/record/backend/service/CategoryService.java
  backend/src/main/java/com/record/backend/service/CommentService.java
  backend/src/main/java/com/record/backend/service/PostService.java
  backend/src/main/java/com/record/backend/service/UserService.java
  backend/src/test/java/com/record/backend/service/CategoryServiceTest.java
  backend/src/test/java/com/record/backend/service/CommentServiceTest.java
  backend/src/test/java/com/record/backend/service/PostServiceTest.java
  backend/src/test/java/com/record/backend/service/UserServiceTest.java
Labels: 🔥 백엔드, 🛠 리팩토링

#56 feat: tag 개발
  backend/src/main/java/com/record/backend/apiController/CategoryApiController.java
  backend/src/main/java/com/record/backend/apiController/CommentApiController.java
  backend/src/main/java/com/record/backend/apiController/PostApiController.java
  backend/src/main/java/com/record/backend/apiController/UserApiController.java
  backend/src/main/java/com/record/backend/controller/TagController.java
  backend/src/main/java/com/record/backend/domain/comment/Comment.java
  backend/src/main/java/com/record/backend/domain/comment/CommentContent.java
  backend/src/main/java/com/record/backend/domain/neighbor/Neighbor.java
  backend/src/main/java/com/record/backend/domain/tag/FilterCriteria.java
  backend/src/main/java/com/record/backend/domain/tag/TagName.java
  backend/src/main/java/com/record/backend/domain/user/User.java
  backend/src/main/java/com/record/backend/dto/category/CategorySaveRequestDto.java
  backend/src/main/java/com/record/backend/dto/category/CategoryUpdateDto.java
  backend/src/main/java/com/record/backend/dto/comment/CommentDto.java
  backend/src/main/java/com/record/backend/dto/comment/CommentResponseDto.java
  backend/src/main/java/com/record/backend/dto/comment/CommentUpdateDto.java
  backend/src/main/java/com/record/backend/dto/post/PostSummaryResponseDto.java
  backend/src/main/java/com/record/backend/dto/post/PostUpdateDto.java
  backend/src/main/java/com/record/backend/dto/user/UserUpdateDto.java
  backend/src/main/java/com/record/backend/repository/comment/CommentQueryRepository.java
  backend/src/main/java/com/record/backend/repository/post/PostRepository.java
  backend/src/main/java/com/record/backend/repository/tag/TagQueryRepository.java
  backend/src/main/java/com/record/backend/service/CategoryService.java
  backend/src/main/java/com/record/backend/service/CommentService.java
  backend/src/main/java/com/record/backend/service/PostService.java
  backend/src/main/java/com/record/backend/service/TagService.java
  backend/src/main/java/com/record/backend/service/UserService.java
  backend/src/test/java/com/record/backend/service/CategoryServiceTest.java
Labels: 🔥 백엔드, 🛠 리팩토링

#57 feat: 비밀번호 확인 에러메세지 추가
  frontend/src/components/Category/CategoryList.js
  frontend/src/components/Category/index.js
  frontend/src/pages/Signup.js
  frontend/src/pages/User.js
Labels: 🌷 프론트, 📱 유아이, 🕹 기능

#58 refactor: post tag, post like 리스트 잠시 삭제
  backend/src/main/java/com/record/backend/apiController/CommentApiController.java
  backend/src/main/java/com/record/backend/apiController/PostApiController.java
  backend/src/main/java/com/record/backend/apiController/UserApiController.java
  backend/src/main/java/com/record/backend/controller/TagController.java
  backend/src/main/java/com/record/backend/domain/post/Post.java
  backend/src/main/java/com/record/backend/domain/post/PostLike.java
  backend/src/main/java/com/record/backend/domain/post/PostLikes.java
  backend/src/main/java/com/record/backend/domain/post/PostTag.java
  backend/src/main/java/com/record/backend/domain/post/Posts.java
  backend/src/main/java/com/record/backend/domain/tag/Tag.java
  backend/src/main/java/com/record/backend/domain/tag/Tags.java
  backend/src/main/java/com/record/backend/domain/user/User.java
  backend/src/main/java/com/record/backend/domain/user/follow/Follow.java
  backend/src/main/java/com/record/backend/domain/user/follow/Followers.java
  backend/src/main/java/com/record/backend/domain/user/follow/Followings.java
  backend/src/main/java/com/record/backend/dto/post/LikePresentationResponse.java
  backend/src/main/java/com/record/backend/dto/post/LikeResponseDto.java
  backend/src/main/java/com/record/backend/dto/post/PostDtoAssembler.java
  backend/src/main/java/com/record/backend/dto/post/PostSummaryResponseDto.java
  backend/src/main/java/com/record/backend/dto/tag/TagResponse.java
  backend/src/main/java/com/record/backend/dto/user/FollowPresentationResponse.java
  backend/src/main/java/com/record/backend/dto/user/FollowRequestDto.java
  backend/src/main/java/com/record/backend/dto/user/FollowResponseDto.java
  backend/src/main/java/com/record/backend/dto/user/FollowSearchRequestDto.java
  backend/src/main/java/com/record/backend/dto/user/UserDtoAssembler.java
  backend/src/main/java/com/record/backend/dto/user/UserSearchResponseDto.java
  backend/src/main/java/com/record/backend/repository/tag/TagRepository.java
  backend/src/main/java/com/record/backend/repository/user/UserRepository.java
  backend/src/main/java/com/record/backend/service/PostService.java
  backend/src/main/java/com/record/backend/service/TagService.java
  backend/src/main/java/com/record/backend/service/UserService.java
Labels: 🔥 백엔드, 🛠 리팩토링
